language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn build-master

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

addons:
  apt:
    packages:
      - libgconf-2-4
