name: Bug report
description: File a bug report
labels: ["bug"]
projects: ["NDS work requests"]
assignees:
  - nikola-nulogy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: Tell us what happened ...
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Walk us through steps that result in a described bug ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: Tell us what should happen ...
  - type: textarea
    id: blocked
    attributes:
      label: Is your team blocked from moving forward by the bug?
      placeholder: Tell us if this problem is blocking your team from delivering value to the customer. Is the customer impact high?
  - type: checkboxes
    id: execution
    attributes:
      label: Who would you like to fix the bug?
      options:
        - label: Myself
        - label: DesignOps
      description: Please check the current Design Ops' [estimated completion time](https://github.com/nulogy/design-system/wiki/How-to-file-NDS-work-request#process) before selecting
  - type: input
    id: due-date
    attributes:
      label: When do you need this by?
  - type: textarea
    id: screenshots
    attributes:
      label: Helpful resources
      placeholder: If applicable, add screenshot(s), video recording(s), and/or sandbox to help us better understand the request.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Tell us more ...
