import * as tokens from "@nulogy/tokens";
import type { DefaultNDSThemeType } from "./theme.type";

type ThemeKey = "desktop" | "touch";

const BASE_THEME = {
  colors: {
    black: tokens.color_base_black,
    blackBlue: tokens.color_base_black_blue,
    darkBlue: tokens.color_base_dark_blue,
    blue: tokens.color_base_blue,
    lightBlue: tokens.color_base_light_blue,
    darkGrey: tokens.color_base_dark_grey,
    midGrey: tokens.color_base_mid_grey,
    grey: tokens.color_base_grey,
    lightGrey: tokens.color_base_light_grey,
    whiteGrey: tokens.color_base_white_grey,
    white: tokens.color_base_white,
    yellow: tokens.color_base_yellow,
    lightYellow: tokens.color_base_light_yellow,
    green: tokens.color_base_green,
    lightGreen: tokens.color_base_light_green,
    red: tokens.color_base_red,
    lightRed: tokens.color_base_light_red,
    categorical1: tokens.color_base_categorical_1,
    categorical2: tokens.color_base_categorical_2,
    categorical3: tokens.color_base_categorical_3,
    categorical4: tokens.color_base_categorical_4,
    categorical5: tokens.color_base_categorical_5,
    categorical6: tokens.color_base_categorical_6,
  },
  fontSizes: {
    smaller: tokens.size_font_smaller,
    small: tokens.size_font_small,
    medium: tokens.size_font_medium,
    large: tokens.size_font_large,
    larger: tokens.size_font_larger,
    largest: tokens.size_font_largest,
    heading1: tokens.size_font_heading_1,
    heading2: tokens.size_font_heading_2,
    heading3: tokens.size_font_heading_3,
    heading4: tokens.size_font_heading_4,
  },
  lineHeights: {
    base: tokens.line_height_base,
    relaxed: "1.66666667",
    smallTextBase: tokens.line_height_small_text_base,
    smallTextCompressed: tokens.line_height_small_text_compressed,
    smallerText: tokens.line_height_smaller_text,
    heading1: tokens.line_height_heading_1,
    heading2: tokens.line_height_heading_2,
    heading3: tokens.line_height_heading_3,
    heading4: tokens.line_height_heading_4,
    title: tokens.line_height_heading_1,
    sectionTitle: tokens.line_height_heading_2,
    subsectionTitle: tokens.line_height_heading_3,
  },
  fontWeights: {
    light: tokens.weight_font_light,
    normal: tokens.weight_font_normal,
    medium: tokens.weight_font_medium,
    bold: tokens.weight_font_bold,
  },
  space: {
    none: tokens.size_base_none,
    half: tokens.size_base_half,
    x1: tokens.size_base_x_1,
    x2: tokens.size_base_x_2,
    x3: tokens.size_base_x_3,
    x4: tokens.size_base_x_4,
    x5: tokens.size_base_x_5,
    x6: tokens.size_base_x_6,
    x8: tokens.size_base_x_8,
  },
  sizes: {
    none: tokens.size_base_none,
    half: tokens.size_base_half,
    x1: tokens.size_base_x_1,
    x2: tokens.size_base_x_2,
    x3: tokens.size_base_x_3,
    x4: tokens.size_base_x_4,
    x5: tokens.size_base_x_5,
    x6: tokens.size_base_x_6,
    x8: tokens.size_base_x_8,
  },
  fonts: {
    base: tokens.font_family_base,
    mono: tokens.font_family_mono,
    sc: tokens.font_family_sc,
  },
  borders: [],
  shadows: {
    small: tokens.shadow_box_small,
    medium: tokens.shadow_box_medium,
    large: tokens.shadow_box_large,
    focus: tokens.shadow_focus,
    error: tokens.shadow_error,
  },
  radii: {
    small: tokens.radius_border_small,
    medium: tokens.radius_border_medium,
    circle: tokens.radius_border_circle,
    rounded: "9999px",
  },
  breakpoints: {
    extraSmall: tokens.size_breakpoint_extra_small,
    small: tokens.size_breakpoint_small,
    medium: tokens.size_breakpoint_medium,
    large: tokens.size_breakpoint_large,
    extraLarge: tokens.size_breakpoint_extra_large,
  },
  zIndices: {
    content: tokens.z_indices_content,
    tabsScollIndicator: tokens.z_indices_tabs_scroll_indicator,
    tabsBar: tokens.z_indices_tabs_bar,
    overlay: tokens.z_indices_overlay,
    aboveOverlay: tokens.z_indices_above_overlay,
    tableHeader: tokens.z_indices_table_header,
    modalHeaderAndFooter: tokens.z_indices_modal_header_and_footer,
    openControl: tokens.z_indices_open_control,
    navBar: tokens.z_indices_nav_bar,
    sidebar: tokens.z_indices_sidebar,
  },
};

const themes: Record<ThemeKey, DefaultNDSThemeType> = {
  desktop: {
    ...BASE_THEME,
  },
  touch: {
    ...BASE_THEME,
    fontSizes: {
      smaller: "18px",
      small: "21px",
      medium: "24px",
      large: "27px",
      larger: "30px",
      largest: "42px",
      heading1: "30px",
      heading2: "24px",
      heading3: "21px",
      heading4: "18px",
    },
    lineHeights: {
      base: "1.33333333",
      relaxed: "1.66666667",
      smallTextBase: "1.33333333",
      smallTextCompressed: "1.33333333",
      smallerText: "1.33333333",
      heading1: "1.33333333",
      heading2: "1.33333333",
      heading3: "1.33333333",
      heading4: "1.33333333",
      title: "1.33333333",
      sectionTitle: "1.33333333",
      subsectionTitle: "1.33333333",
    },
    space: {
      none: "0px",
      half: "5.4px",
      x1: "10.8px",
      x2: "21.6px",
      x3: "32.4px",
      x4: "43.2px",
      x5: "54px",
      x6: "64.8px",
      x8: "75.6px",
    },
    sizes: {
      none: "0px",
      half: "5.4px",
      x1: "10.8px",
      x2: "21.6px",
      x3: "32.4px",
      x4: "43.2px",
      x5: "54px",
      x6: "64.8px",
      x8: "75.6px",
    },
    radii: {
      small: "2.7px",
      medium: "5.4px",
      circle: "50%",
      rounded: "9999px",
    },
  },
};

export { themes };
export const { desktop, touch } = themes;
