// Materials data for consumption reports

export const materialsData1 = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Acetaminophen 500mg",
    lotCode: "LOT-ACET-001",
    expiryDate: "2026-03-15",
    palletNumber: "PAL-001",
    quantity: "2.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Microcrystalline cellulose",
    lotCode: "LOT-MCC-001",
    expiryDate: "2026-04-20",
    palletNumber: "PAL-002",
    quantity: "1.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Croscarmellose sodium",
    lotCode: "LOT-CCS-001",
    expiryDate: "2026-05-10",
    palletNumber: "PAL-003",
    quantity: "0.3",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Magnesium stearate",
    lotCode: "LOT-MS-001",
    expiryDate: "2026-06-15",
    palletNumber: "PAL-004",
    quantity: "0.1",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "Hydroxypropyl methylcellulose",
    lotCode: "LOT-HPMC-001",
    expiryDate: "2026-07-20",
    palletNumber: "PAL-005",
    quantity: "0.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Talc powder",
    lotCode: "LOT-TALC-001",
    expiryDate: "2026-08-25",
    palletNumber: "PAL-006",
    quantity: "0.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "007",
    item: "FD&C Blue #2",
    lotCode: "LOT-BLUE-001",
    expiryDate: "2026-09-30",
    palletNumber: "PAL-007",
    quantity: "0.02",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "008",
    item: "Sodium benzoate",
    lotCode: "LOT-SB-001",
    expiryDate: "2026-10-15",
    palletNumber: "PAL-008",
    quantity: "0.05",
    uom: "kg",
  },
];

export const materialsData2 = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Ibuprofen 200mg",
    lotCode: "LOT-IBU-002",
    expiryDate: "2026-04-10",
    palletNumber: "PAL-009",
    quantity: "1.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Povidone K30",
    lotCode: "LOT-PVP-002",
    expiryDate: "2026-05-15",
    palletNumber: "PAL-010",
    quantity: "0.9",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Sodium starch glycolate",
    lotCode: "LOT-SSG-002",
    expiryDate: "2026-06-20",
    palletNumber: "PAL-011",
    quantity: "0.6",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Magnesium stearate",
    lotCode: "LOT-MS-002",
    expiryDate: "2026-07-25",
    palletNumber: "PAL-012",
    quantity: "0.3",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "Colloidal silicon dioxide",
    lotCode: "LOT-CSD-002",
    expiryDate: "2026-08-30",
    palletNumber: "PAL-013",
    quantity: "0.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Titanium dioxide",
    lotCode: "LOT-TD-002",
    expiryDate: "2026-09-05",
    palletNumber: "PAL-014",
    quantity: "0.1",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "007",
    item: "FD&C Yellow No. 6",
    lotCode: "LOT-FD6-002",
    expiryDate: "2026-10-10",
    palletNumber: "PAL-015",
    quantity: "0.05",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "008",
    item: "Microcrystalline cellulose",
    lotCode: "LOT-MCC-002",
    expiryDate: "2026-11-15",
    palletNumber: "PAL-016",
    quantity: "2.5",
    uom: "kg",
  },
];

export const materialsData5A = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Ibuprofen 200mg",
    lotCode: "LOT-IBU-005A",
    expiryDate: "2026-05-10",
    palletNumber: "PAL-017",
    quantity: "1.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Povidone K30",
    lotCode: "LOT-PVP-005A",
    expiryDate: "2026-06-15",
    palletNumber: "PAL-018",
    quantity: "0.9",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Sodium starch glycolate",
    lotCode: "LOT-SSG-005A",
    expiryDate: "2026-07-20",
    palletNumber: "PAL-019",
    quantity: "0.4",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Stearic acid",
    lotCode: "LOT-SA-005A",
    expiryDate: "2026-08-25",
    palletNumber: "PAL-020",
    quantity: "0.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "FD&C Red #40",
    lotCode: "LOT-RED-005A",
    expiryDate: "2026-09-30",
    palletNumber: "PAL-021",
    quantity: "0.05",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Silicon dioxide",
    lotCode: "LOT-SD-005A",
    expiryDate: "2026-10-15",
    palletNumber: "PAL-022",
    quantity: "0.3",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "007",
    item: "Aspartame",
    lotCode: "LOT-ASP-005A",
    expiryDate: "2026-11-20",
    palletNumber: "PAL-023",
    quantity: "0.1",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "008",
    item: "Mint flavor",
    lotCode: "LOT-MF-005A",
    expiryDate: "2026-12-25",
    palletNumber: "PAL-024",
    quantity: "0.02",
    uom: "kg",
  },
];

export const materialsData5B = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Ibuprofen 200mg",
    lotCode: "LOT-IBU-005B",
    expiryDate: "2026-05-10",
    palletNumber: "PAL-025",
    quantity: "0.9",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Povidone K30",
    lotCode: "LOT-PVP-005B",
    expiryDate: "2026-06-15",
    palletNumber: "PAL-026",
    quantity: "0.45",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Sodium starch glycolate",
    lotCode: "LOT-SSG-005B",
    expiryDate: "2026-07-20",
    palletNumber: "PAL-027",
    quantity: "0.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Stearic acid",
    lotCode: "LOT-SA-005B",
    expiryDate: "2026-08-25",
    palletNumber: "PAL-028",
    quantity: "0.1",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "FD&C Red #40",
    lotCode: "LOT-RED-005B",
    expiryDate: "2026-09-30",
    palletNumber: "PAL-029",
    quantity: "0.025",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Silicon dioxide",
    lotCode: "LOT-SD-005B",
    expiryDate: "2026-10-15",
    palletNumber: "PAL-030",
    quantity: "0.15",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "007",
    item: "Aspartame",
    lotCode: "LOT-ASP-005B",
    expiryDate: "2026-11-20",
    palletNumber: "PAL-031",
    quantity: "0.05",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "008",
    item: "Mint flavor",
    lotCode: "LOT-MF-005B",
    expiryDate: "2026-12-25",
    palletNumber: "PAL-032",
    quantity: "0.01",
    uom: "kg",
  },
];

export const materialsData6A = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Acetaminophen 500mg",
    lotCode: "LOT-ACET-006A",
    expiryDate: "2026-06-15",
    palletNumber: "PAL-033",
    quantity: "3.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Microcrystalline cellulose",
    lotCode: "LOT-MCC-006A",
    expiryDate: "2026-07-20",
    palletNumber: "PAL-034",
    quantity: "1.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Croscarmellose sodium",
    lotCode: "LOT-CCS-006A",
    expiryDate: "2026-08-25",
    palletNumber: "PAL-035",
    quantity: "0.4",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Magnesium stearate",
    lotCode: "LOT-MS-006A",
    expiryDate: "2026-09-30",
    palletNumber: "PAL-036",
    quantity: "0.15",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "Hydroxypropyl methylcellulose",
    lotCode: "LOT-HPMC-006A",
    expiryDate: "2026-10-15",
    palletNumber: "PAL-037",
    quantity: "1.0",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Talc powder",
    lotCode: "LOT-TALC-006A",
    expiryDate: "2026-11-20",
    palletNumber: "PAL-038",
    quantity: "0.3",
    uom: "kg",
  },
];

export const materialsData6B = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Acetaminophen 500mg",
    lotCode: "LOT-ACET-006B",
    expiryDate: "2026-06-15",
    palletNumber: "PAL-041",
    quantity: "1.7",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Microcrystalline cellulose",
    lotCode: "LOT-MCC-006B",
    expiryDate: "2026-07-20",
    palletNumber: "PAL-042",
    quantity: "0.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Croscarmellose sodium",
    lotCode: "LOT-CCS-006B",
    expiryDate: "2026-08-25",
    palletNumber: "PAL-043",
    quantity: "0.2",
    uom: "kg",
  },
];

export const materialsData7A = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Pending - Acetaminophen 500mg",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - Microcrystalline cellulose",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - Croscarmellose sodium",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - Magnesium stearate",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - Hydroxypropyl methylcellulose",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - Talc powder",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - FD&C Blue #2",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
  {
    item: "Pending - Sodium benzoate",
    lotCode: "TBD",
    expiryDate: "TBD",
    palletNumber: "TBD",
    quantity: "TBD",
    uom: "TBD",
  },
];

export const materialsData7B = [
  // Base materials (8 items)
  {
    item: "Acetaminophen 500mg",
    lotCode: "LOT-ACET-007B",
    expiryDate: "2026-12-15",
    palletNumber: "PAL-049",
    quantity: "4.0",
    uom: "kg",
  },
  {
    item: "Microcrystalline cellulose",
    lotCode: "LOT-MCC-007B",
    expiryDate: "2027-01-20",
    palletNumber: "PAL-050",
    quantity: "2.0",
    uom: "kg",
  },
  {
    item: "Croscarmellose sodium",
    lotCode: "LOT-CCS-007B",
    expiryDate: "2027-02-25",
    palletNumber: "PAL-051",
    quantity: "0.5",
    uom: "kg",
  },
  {
    item: "Magnesium stearate",
    lotCode: "LOT-MS-007B",
    expiryDate: "2027-03-30",
    palletNumber: "PAL-052",
    quantity: "0.2",
    uom: "kg",
  },
  {
    item: "Hydroxypropyl methylcellulose",
    lotCode: "LOT-HPMC-007B",
    expiryDate: "2027-04-15",
    palletNumber: "PAL-053",
    quantity: "1.5",
    uom: "kg",
  },
  {
    item: "Talc powder",
    lotCode: "LOT-TALC-007B",
    expiryDate: "2027-05-20",
    palletNumber: "PAL-054",
    quantity: "0.8",
    uom: "kg",
  },
  {
    item: "FD&C Blue #2",
    lotCode: "LOT-BLUE-007B",
    expiryDate: "2027-06-25",
    palletNumber: "PAL-055",
    quantity: "0.04",
    uom: "kg",
  },
  {
    item: "Sodium benzoate",
    lotCode: "LOT-SB-007B",
    expiryDate: "2027-07-30",
    palletNumber: "PAL-056",
    quantity: "0.1",
    uom: "kg",
  },
];
