// Materials data for consumption reports
export const materialsData1 = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Acetaminophen 500mg",
    customerLotCode: "LOT-123",
    supplierLotCode: "SUP-123",
    expiryDate: "2026-03-15",
    palletNumber: "PAL-001",
    quantity: "2.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Microcrystalline cellulose",
    customerLotCode: "LOT-456",
    supplierLotCode: "SUP-456",
    expiryDate: "2026-04-20",
    palletNumber: "PAL-002",
    quantity: "1.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Croscarmellose sodium",
    customerLotCode: "LOT-789",
    supplierLotCode: "SUP-789",
    expiryDate: "2026-05-10",
    palletNumber: "PAL-003",
    quantity: "0.3",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Magnesium stearate",
    customerLotCode: "LOT-012",
    supplierLotCode: "SUP-012",
    expiryDate: "2026-06-15",
    palletNumber: "PAL-004",
    quantity: "0.1",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "Hydroxypropyl methylcellulose",
    customerLotCode: "LOT-345",
    supplierLotCode: "SUP-345",
    expiryDate: "2026-07-20",
    palletNumber: "PAL-005",
    quantity: "0.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Talc powder",
    customerLotCode: "LOT-678",
    supplierLotCode: "SUP-678",
    expiryDate: "2026-08-25",
    palletNumber: "PAL-006",
    quantity: "0.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "007",
    item: "FD&C Blue #2",
    customerLotCode: "LOT-901",
    supplierLotCode: "SUP-901",
    expiryDate: "2026-09-30",
    palletNumber: "PAL-007",
    quantity: "0.02",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "008",
    item: "Sodium benzoate",
    customerLotCode: "LOT-234",
    supplierLotCode: "SUP-234",
    expiryDate: "2026-10-15",
    palletNumber: "PAL-008",
    quantity: "0.05",
    uom: "kg",
  },
];

export const materialsData2 = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Ibuprofen 200mg",
    customerLotCode: "LOT-567",
    supplierLotCode: "SUP-567",
    expiryDate: "2026-04-10",
    palletNumber: "PAL-009",
    quantity: "1.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Lactose monohydrate",
    customerLotCode: "LOT-890",
    supplierLotCode: "SUP-890",
    expiryDate: "2026-05-15",
    palletNumber: "PAL-010",
    quantity: "2.1",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Pregelatinized starch",
    customerLotCode: "LOT-123",
    supplierLotCode: "SUP-123",
    expiryDate: "2026-06-20",
    palletNumber: "PAL-011",
    quantity: "0.4",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Stearic acid",
    lotCode: "LOT-SA-002",
    expiryDate: "2026-07-25",
    palletNumber: "PAL-012",
    quantity: "0.12",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "Hydroxypropyl methylcellulose",
    lotCode: "LOT-HPMC-002",
    expiryDate: "2026-08-30",
    palletNumber: "PAL-013",
    quantity: "0.25",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "Titanium dioxide",
    lotCode: "LOT-TD-002",
    expiryDate: "2026-09-05",
    palletNumber: "PAL-014",
    quantity: "0.03",
    uom: "kg",
  },
];

export const materialsData5A = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Aspirin 325mg",
    lotCode: "LOT-ASP-001",
    expiryDate: "2026-05-15",
    palletNumber: "PAL-015",
    quantity: "4.0",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Corn starch",
    lotCode: "LOT-CS-001",
    expiryDate: "2026-06-20",
    palletNumber: "PAL-016",
    quantity: "2.0",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Calcium carbonate",
    lotCode: "LOT-CC-001",
    expiryDate: "2026-07-25",
    palletNumber: "PAL-017",
    quantity: "0.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Carnauba wax",
    lotCode: "LOT-CW-001",
    expiryDate: "2026-08-30",
    palletNumber: "PAL-018",
    quantity: "0.08",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "FD&C Yellow No. 6",
    lotCode: "LOT-FD6-001",
    expiryDate: "2026-09-05",
    palletNumber: "PAL-019",
    quantity: "0.01",
    uom: "kg",
  },
];

export const materialsData5B = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Naproxen sodium 220mg",
    lotCode: "LOT-NAP-001",
    expiryDate: "2026-10-10",
    palletNumber: "PAL-020",
    quantity: "3.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Dibasic calcium phosphate",
    lotCode: "LOT-DCP-001",
    expiryDate: "2026-11-15",
    palletNumber: "PAL-021",
    quantity: "1.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Sodium lauryl sulfate",
    lotCode: "LOT-SLS-001",
    expiryDate: "2026-12-20",
    palletNumber: "PAL-022",
    quantity: "0.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Opadry II",
    lotCode: "LOT-OP2-001",
    expiryDate: "2027-01-25",
    palletNumber: "PAL-023",
    quantity: "0.15",
    uom: "kg",
  },
];

export const materialsData6A = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Metformin HCl 500mg",
    lotCode: "LOT-MET-001",
    expiryDate: "2026-08-15",
    palletNumber: "PAL-024",
    quantity: "5.0",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Povidone K90",
    lotCode: "LOT-PV90-001",
    expiryDate: "2026-09-20",
    palletNumber: "PAL-025",
    quantity: "0.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Sodium carboxymethylcellulose",
    lotCode: "LOT-SCMC-001",
    expiryDate: "2026-10-25",
    palletNumber: "PAL-026",
    quantity: "0.3",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Polysorbate 80",
    lotCode: "LOT-P80-001",
    expiryDate: "2026-11-30",
    palletNumber: "PAL-027",
    quantity: "0.05",
    uom: "kg",
  },
];

export const materialsData6B = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Glipizide 5mg",
    lotCode: "LOT-GLP-001",
    expiryDate: "2026-12-05",
    palletNumber: "PAL-028",
    quantity: "0.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Lactose anhydrous",
    lotCode: "LOT-LA-001",
    expiryDate: "2027-01-10",
    palletNumber: "PAL-029",
    quantity: "2.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Croscarmellose sodium",
    lotCode: "LOT-CCS-002",
    expiryDate: "2027-02-15",
    palletNumber: "PAL-030",
    quantity: "0.4",
    uom: "kg",
  },
];

export const materialsData7A = [
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Omeprazole 20mg",
    lotCode: "LOT-OME-001",
    expiryDate: "2026-09-15",
    palletNumber: "PAL-031",
    quantity: "2.0",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Mannitol",
    lotCode: "LOT-MAN-001",
    expiryDate: "2026-10-20",
    palletNumber: "PAL-032",
    quantity: "1.5",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Hydroxypropyl cellulose",
    lotCode: "LOT-HPC-001",
    expiryDate: "2026-11-25",
    palletNumber: "PAL-033",
    quantity: "0.3",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Sodium hydroxide",
    lotCode: "LOT-SH-001",
    expiryDate: "2026-12-30",
    palletNumber: "PAL-034",
    quantity: "0.02",
    uom: "kg",
  },
];

export const materialsData7B = [
  // Base materials (8 items)
  {
    subcomponentConsumptionRecordItem: "001",
    item: "Lansoprazole 30mg",
    lotCode: "LOT-LAN-001",
    expiryDate: "2027-01-05",
    palletNumber: "PAL-035",
    quantity: "1.8",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "002",
    item: "Sucrose",
    lotCode: "LOT-SUC-001",
    expiryDate: "2027-02-10",
    palletNumber: "PAL-036",
    quantity: "1.2",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "003",
    item: "Gelatin",
    lotCode: "LOT-GEL-001",
    expiryDate: "2027-03-15",
    palletNumber: "PAL-037",
    quantity: "0.4",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "004",
    item: "Talc",
    lotCode: "LOT-TALC-002",
    expiryDate: "2027-04-20",
    palletNumber: "PAL-038",
    quantity: "0.06",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "005",
    item: "Titanium dioxide",
    lotCode: "LOT-TD-002",
    expiryDate: "2027-05-25",
    palletNumber: "PAL-039",
    quantity: "0.04",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "006",
    item: "FD&C Blue No. 1",
    lotCode: "LOT-FD1-001",
    expiryDate: "2027-06-30",
    palletNumber: "PAL-040",
    quantity: "0.01",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "007",
    item: "Iron oxide red",
    lotCode: "LOT-IOR-001",
    expiryDate: "2027-07-05",
    palletNumber: "PAL-041",
    quantity: "0.005",
    uom: "kg",
  },
  {
    subcomponentConsumptionRecordItem: "008",
    item: "Iron oxide yellow",
    lotCode: "LOT-IOY-001",
    expiryDate: "2027-08-10",
    palletNumber: "PAL-042",
    quantity: "0.005",
    uom: "kg",
  },
];
